// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWTWHffqUwCkDv8h1GerA4JxsHffZR81g',
    appId: '1:417178454465:android:b6d4c78d1a4bc5a0bf4740',
    messagingSenderId: '417178454465',
    projectId: 'mynotes-andrei',
    storageBucket: 'mynotes-andrei.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpmOxJrPCfIYRE6V9qE7vLA3Lrx7pBQKQ',
    appId: '1:417178454465:ios:b9da9e4d43fb5aafbf4740',
    messagingSenderId: '417178454465',
    projectId: 'mynotes-andrei',
    storageBucket: 'mynotes-andrei.appspot.com',
    iosClientId: '417178454465-abvdd415poae3os4jo9fqief4fr9pr2c.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynote',
  );
}
